apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-test
  namespace: tnf
spec:
  engineState: "active"
  annotationCheck: "false"
  appinfo:
    appns: {{APP_NAMESPACE}} 
    applabel: {{APP_LABEL}}
    appkind: {{APP_KIND}} 
  chaosServiceAccount: test-sa
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
          # provided as true for the force deletion of pod
          # supports true and false value
            - name: FORCE
              value: 'true'
            - name: TOTAL_CHAOS_DURATION
              value: '60'
